VERILOG_SOURCES = $(PWD)/qnb.v 
# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file:
TOPLEVEL=top
# MODULE is the name of the Python test file:
MODULE=test_coco

include $(shell cocotb-config --makefiles)/Makefile.sim